### PR TITLE
Move NotNullWhenAttribute to FakeItEasy.Analyzer.Shared directory

### PR DESCRIPTION
**Pull request by blairconrad**
Contributes to FakeItEasy/FakeItEasy#1735.

### CODE REVIEW

**Comment by thomaslevesque** [comment]
Thanks @blairconrad. I can't merge yet, it needs to be rebase first.

**Comment by blairconrad** [comment]
Rebased!

**Comment by blairconrad** [comment]
And thanks for the merge!

**Comment by thomaslevesque** [comment]
Thanks!

**Pull request merged**
