### PR TITLE
Freeze documentation-building tools versions

### PR DESCRIPTION
**Pull request by blairconrad**

### CODE REVIEW

**Review by thomaslevesque — DISMISSED** [review]
Thanks @blairconrad!

**Review by thomaslevesque — APPROVED** [review]

**Comment by blairconrad** [comment]
Thanks, @thomaslevesque!

**Comment by blairconrad** [comment]
@thomaslevesque, I updated fakeiteasy.github.io locally with the new packages, and there was only a change in the sitemap (the lastmod time), so I don't think we need to update the docs site at this time.

**Comment by thomaslevesque** [comment]
Fine by me!

**Pull request merged**
